-- =============================================================
-- MedFlow Database Schema
-- Generated from: backend/src/README.md (ERD)
-- =============================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- =============================================================
-- 1. ROLE ENUM
-- Single source of truth for all role values
-- =============================================================
CREATE TYPE user_role AS ENUM ('patient', 'doctor', 'nurse', 'admin');


-- =============================================================
-- 2. PER-ROLE SEQUENCES
-- Each role gets its own counter for human-readable public IDs
-- =============================================================
CREATE SEQUENCE seq_d;  -- Doctors  → D-0001, D-0002 …
CREATE SEQUENCE seq_n;  -- Nurses   → N-0001, N-0002 …
CREATE SEQUENCE seq_p;  -- Patients → P-0001, P-0002 …
CREATE SEQUENCE seq_a;  -- Admins   → A-0001, A-0002 …


-- =============================================================
-- AUTH_USERS
-- Stores authentication credentials (mirrors Supabase auth.users)
-- =============================================================
CREATE TABLE auth_users (
    id            UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
    email         TEXT  NOT NULL UNIQUE,
    password_auth TEXT  NOT NULL
);


-- =============================================================
-- PROFILES
-- One profile per auth user.
-- • role     – enforced via enum, not a free-text field
-- • public_id – human-readable label (D-0001, N-0004, P-0012, A-0001)
--               auto-generated by trg_public_id before insert
-- • UNIQUE(id, role) – allows composite FK references from child tables
--   so Postgres can enforce "this FK must point at a doctor / nurse"
-- =============================================================
CREATE TABLE profiles (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name  TEXT        NOT NULL,
    email      TEXT        NOT NULL UNIQUE,
    role       user_role   NOT NULL,
    public_id  TEXT        UNIQUE,          -- set by trigger, NULL until insert fires
    phone      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- AUTH_USERS ||--|| PROFILES (same UUID, 1-to-1)
    CONSTRAINT fk_profiles_auth_user
        FOREIGN KEY (id) REFERENCES auth_users (id) ON DELETE CASCADE,

    -- Guardrail: prefix letter must match the role
    --   D-0001 → doctor | N-0004 → nurse | P-0012 → patient | A-0001 → admin
    CONSTRAINT public_id_matches_role CHECK (
        public_id ~ '^[DNPA]-[0-9]{4,}$' AND
        LEFT(public_id, 1) = CASE role
            WHEN 'doctor'  THEN 'D'
            WHEN 'nurse'   THEN 'N'
            WHEN 'patient' THEN 'P'
            WHEN 'admin'   THEN 'A'
        END
    ),

    -- Exposes (id, role) as a unique pair so child tables can use
    -- composite foreign keys to enforce role constraints
    CONSTRAINT uq_profiles_id_role UNIQUE (id, role)
);


-- =============================================================
-- 3. PUBLIC_ID AUTO-GENERATE TRIGGER
-- Runs BEFORE INSERT so the row is never stored without a public_id
-- =============================================================
CREATE FUNCTION set_public_id() RETURNS trigger AS $$
BEGIN
    NEW.public_id := CASE NEW.role
        WHEN 'doctor'  THEN 'D-' || lpad(nextval('seq_d')::text, 4, '0')
        WHEN 'nurse'   THEN 'N-' || lpad(nextval('seq_n')::text, 4, '0')
        WHEN 'patient' THEN 'P-' || lpad(nextval('seq_p')::text, 4, '0')
        WHEN 'admin'   THEN 'A-' || lpad(nextval('seq_a')::text, 4, '0')
    END;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_public_id
    BEFORE INSERT ON profiles
    FOR EACH ROW EXECUTE FUNCTION set_public_id();


-- =============================================================
-- PATIENTS
-- Extended patient-specific data linked to a profile.
-- user_id points at a profile whose role = 'patient' (composite FK).
-- =============================================================
CREATE TABLE patients (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID        NOT NULL,
    -- Composite FK phantom column: must equal 'patient' to compile the FK
    user_role     user_role   NOT NULL DEFAULT 'patient' CHECK (user_role = 'patient'),
    date_of_birth DATE,
    blood_type    TEXT,
    allergies     TEXT,
    status        TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ,

    -- PROFILES ||--o| PATIENTS  (role-enforced: must be a 'patient' profile)
    CONSTRAINT fk_patients_profile
        FOREIGN KEY (user_id, user_role) REFERENCES profiles (id, role) ON DELETE CASCADE
);


-- =============================================================
-- DOCTOR_PATIENT_ASSIGNMENTS
-- Links a doctor profile to a patient.
-- Composite FK on doctor_id ensures it can only point at a doctor.
-- =============================================================
CREATE TABLE doctor_patient_assignments (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id   UUID        NOT NULL,
    -- Phantom column; value is always 'doctor', enforced by CHECK + FK
    doctor_role user_role   NOT NULL DEFAULT 'doctor' CHECK (doctor_role = 'doctor'),
    patient_id  UUID        NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- PROFILES ||--o{ DOCTOR_PATIENT_ASSIGNMENTS  (role-enforced: doctor only)
    CONSTRAINT fk_assignments_doctor
        FOREIGN KEY (doctor_id, doctor_role) REFERENCES profiles (id, role) ON DELETE CASCADE,

    -- PATIENTS ||--o{ DOCTOR_PATIENT_ASSIGNMENTS
    CONSTRAINT fk_assignments_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
);


-- =============================================================
-- CLINICAL_NOTES
-- Doctor-authored notes per patient visit.
-- Composite FK on doctor_id ensures it can only point at a doctor.
-- =============================================================
CREATE TABLE clinical_notes (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id  UUID        NOT NULL,
    doctor_id   UUID        NOT NULL,
    -- Phantom column; value is always 'doctor', enforced by CHECK + FK
    doctor_role user_role   NOT NULL DEFAULT 'doctor' CHECK (doctor_role = 'doctor'),
    diagnosis   TEXT,
    observation TEXT,
    plan        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ,

    -- PATIENTS ||--o{ CLINICAL_NOTES
    CONSTRAINT fk_clinical_notes_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,

    -- PROFILES ||--o{ CLINICAL_NOTES  (role-enforced: doctor only)
    --   Rejects any clinical_note whose doctor_id belongs to a nurse or patient
    CONSTRAINT fk_clinical_notes_doctor
        FOREIGN KEY (doctor_id, doctor_role) REFERENCES profiles (id, role) ON DELETE CASCADE
);


-- =============================================================
-- CARE_NOTES
-- Nurse-authored notes (vitals, observations) per patient.
-- Composite FK on nurse_id ensures it can only point at a nurse.
-- =============================================================
CREATE TABLE care_notes (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id  UUID        NOT NULL,
    nurse_id    UUID        NOT NULL,
    -- Phantom column; value is always 'nurse', enforced by CHECK + FK
    nurse_role  user_role   NOT NULL DEFAULT 'nurse' CHECK (nurse_role = 'nurse'),
    vitals      TEXT,
    observation TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ,

    -- PATIENTS ||--o{ CARE_NOTES
    CONSTRAINT fk_care_notes_patient
        FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,

    -- PROFILES ||--o{ CARE_NOTES  (role-enforced: nurse only)
    --   Rejects any care_note whose nurse_id belongs to a doctor or patient
    CONSTRAINT fk_care_notes_nurse
        FOREIGN KEY (nurse_id, nurse_role) REFERENCES profiles (id, role) ON DELETE CASCADE
);
